package:
  name: simcat
  version: '0.0.4'

source:
  url: https://github.com/eaton-lab/simcat/archive/0.0.4.tar.gz
  sha256: 1db292fa652d14dd138ee021af28b0f448f07e70226745ae324210ec490fbf77

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  noarch: python
  
requirements:
  host:
    - pip
    - python
  run:
    - python
    - ipcoal
    - h5py
    - numba
    - future
    - ipyparallel
    - ipywidgets

test:
  imports:
    - ipcoal

about:
  home: http://github.com/eaton-lab/ipcoal
  license: GPLv3
  summary: Interactive and reproducible simulation and analysis of gene trees.
